server:
  port: 9100

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.199.77.187:3306/online_examination?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    #    url: jdbc:mysql://localhost:3306/online_examination?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
#必须加，不然接口文档的参数说明不起作用
knife4j:
  enable: true
logging:
  pattern:
    level: debug